on:
  push:
    branches: [main, master]
  schedule:
    - cron: '5 12-15 * * 1-5'


name: Render Quarto doc

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Clona esse repositório
        uses: actions/checkout@v3

      - name: Instalar o R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          use-public-rspm: true

      - name: Instalar pacotes de R
        uses: r-lib/actions/setup-renv@v2

      - name: Extração, transformação, disponibilização
        run: |
          Source("./R/00_pacotes.R")
          Source("./R/01_funcoes_uteis.R")
          Source("./R/02_extracao.R")
          Source("./R/03_transformacao.R")
          Source("./R/04_disponibilizacao.R")
        shell: Rscript {0}
          

      - name: Instalar o Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderiza o relatório
        run: |
          cp -r report/* ./
          quarto render index.qmd
          rm -rf report contents resources index.qmd macro_report_priv.Rproj
          mv index.html docs

      - name: Create PDF doc
        run: |
          pagedown::chrome_print(input = "docs/index.html", format = "pdf", options = list(paperWidth = 11, paperHeight = 11))
        shell: Rscript {0}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualização de aplicações